<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-02T07:44:13 IST" name="Suite" finished-at="2023-05-02T07:44:13 IST" duration-ms="223">
    <groups>
      <group name="logout">
        <method signature="testR13.TestCaseThree()[pri:0, instance:test.com.testR13@52e6fdee]" name="TestCaseThree" class="test.com.testR13"/>
      </group> <!-- logout -->
      <group name="login">
        <method signature="testR13.TestCaseOne()[pri:0, instance:test.com.testR13@52e6fdee]" name="TestCaseOne" class="test.com.testR13"/>
        <method signature="testR13.TestCaseTwo()[pri:0, instance:test.com.testR13@52e6fdee]" name="TestCaseTwo" class="test.com.testR13"/>
      </group> <!-- login -->
    </groups>
    <test started-at="2023-05-02T07:44:13 IST" name="Test" finished-at="2023-05-02T07:44:13 IST" duration-ms="223">
      <class name="test.com.testR13">
        <test-method signature="TestCaseOne()[pri:0, instance:test.com.testR13@52e6fdee]" started-at="2023-05-02T07:44:13 IST" name="TestCaseOne" finished-at="2023-05-02T07:44:13 IST" duration-ms="42" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCaseOne -->
        <test-method signature="TestCaseTwo()[pri:0, instance:test.com.testR13@52e6fdee]" started-at="2023-05-02T07:44:13 IST" name="TestCaseTwo" finished-at="2023-05-02T07:44:13 IST" duration-ms="22" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:147)
at test.com.testR13.TestCaseTwo(testR13.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCaseTwo -->
        <test-method signature="TestCaseThree()[pri:0, instance:test.com.testR13@52e6fdee]" started-at="2023-05-02T07:44:13 IST" name="TestCaseThree" depends-on-groups="login" finished-at="2023-05-02T07:44:13 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testR13.TestCaseThree()[pri:0, instance:test.com.testR13@52e6fdee] depends on not successfully finished methods in group "login"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testR13.TestCaseThree()[pri:0, instance:test.com.testR13@52e6fdee] depends on not successfully finished methods in group "login"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCaseThree -->
      </class> <!-- test.com.testR13 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
